trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
    zipAfterPublish: true
    modifyOutputPath: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Output'
    ArtifactName: 'backend'
    publishLocation: 'Container'
    
- task: NodeTool@0
  inputs:
    versionSource: 'spec'
    versionSpec: '18.12.0'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm install
      npm build
    workingDirectory: 'frontend'