trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '-o $(Build.ArtifactStagingDirectory)/Output'
    zipAfterPublish: true
    modifyOutputPath: true
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Backend Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Output'
    ArtifactName: 'backend'
    publishLocation: 'Container'
    
# - task: NodeTool@0
#   displayName: 'Install NodeJS'
#   inputs:
#     versionSource: 'spec'
#     versionSpec: '18.12.0'
    
- task: Bash@3
  displayName: 'Build Frontend'
  inputs:
    targetType: 'inline'
    script: |
      npm install
      npm run build
    workingDirectory: 'frontend'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Frontend Artifact'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/frontend/.next'
    ArtifactName: 'frontend'
    publishLocation: 'Container'

    